### ISSUE TITLE
Why it's expect semicolons inside style in ex 4 - proptypes? (Exercise before it also requires semicolon)

### ISSUE THREAD

**Issue by moseskarunia** [workshopper/learnyoureact#138] opened 2018-05-17 06:10 UTC
If I verify it:

```
M:\Work\Learning Files\learnyoureact>learnyoureact verify program.js
Express server is up on port 3000

Your submission results compared to the expected:

────────────────────────────────────────────────────────────────────────────────

1.  ACTUAL:    "<!DOCTYPE html>"
1.  EXPECTED:  "<!DOCTYPE html>"

2.  ACTUAL:    "<div class=\"todoBox\">"
2.  EXPECTED:  "<div class=\"todoBox\">"

3.  ACTUAL:    "    <h1>Todos</h1>"
3.  EXPECTED:  "    <h1>Todos</h1>"

4.  ACTUAL:    "    <div class=\"todoList\">"
4.  EXPECTED:  "    <div class=\"todoList\">"

5.  ACTUAL:    "        <table style=\"border:2px solid black\">"
5.  EXPECTED:  "        <table style=\"border:2px solid black;\">"

6.  ACTUAL:    "            <tbody>"
6.  EXPECTED:  "            <tbody>"

7.  ACTUAL:    "                <tr>"
7.  EXPECTED:  "                <tr>"

8.  ACTUAL:    "                    <td style=\"border:1px solid black\">Shopping</td>"
8.  EXPECTED:  "                    <td style=\"border:1px solid black;\">Shopping</td>"

9.  ACTUAL:    "                    <td style=\"border:1px solid black\">Milk</td>"
9.  EXPECTED:  "                    <td style=\"border:1px solid black;\">Milk</td>"

10. ACTUAL:    "                </tr>"
10. EXPECTED:  "                </tr>"

11. ACTUAL:    "                <tr>"
11. EXPECTED:  "                <tr>"

12. ACTUAL:    "                    <td style=\"border:1px solid black\">Hair cut</td>"
12. EXPECTED:  "                    <td style=\"border:1px solid black;\">Hair cut</td>"

13. ACTUAL:    "                    <td style=\"border:1px solid black\">13:00</td>"
13. EXPECTED:  "                    <td style=\"border:1px solid black;\">13:00</td>"

14. ACTUAL:    "                </tr>"
14. EXPECTED:  "                </tr>"

15. ACTUAL:    "                <tr>"
15. EXPECTED:  "                <tr>"

16. ACTUAL:    "                    <td style=\"border:1px solid black\">Learn React</td>"
16. EXPECTED:  "                    <td style=\"border:1px solid black;\">Learn React</td>"

17. ACTUAL:    "                    <td style=\"border:1px solid black\">15:00</td>"
17. EXPECTED:  "                    <td style=\"border:1px solid black;\">15:00</td>"

18. ACTUAL:    "                </tr>"
18. EXPECTED:  "                </tr>"

19. ACTUAL:    "            </tbody>"
19. EXPECTED:  "            </tbody>"

20. ACTUAL:    "        </table>"
20. EXPECTED:  "        </table>"

21. ACTUAL:    "    </div>"
21. EXPECTED:  "    </div>"

22. ACTUAL:    "    <div class=\"todoForm\">I am a TodoForm.</div>"
22. EXPECTED:  "    <div class=\"todoForm\">I am a TodoForm.</div>"

23. ACTUAL:    "</div>"
23. EXPECTED:  "</div>"


────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!

# FAIL

Your solution to PROPTYPES didn't pass. Try again!
```

If I run it, there's below warning:

```
Warning: Style property values shouldn't contain a semicolon. Try "border: 2px solid black" instead.
    in table
    in div
    in TodoList
    in div
    in TodoBox
Warning: Style property values shouldn't contain a semicolon. Try "border: 1px solid black" instead.
    in td
    in tr
    in Todo
    in tbody
    in table
    in div
    in TodoList
    in div
    in TodoBox
```

But if I remove the semicolon, I can't pass the verification.
It's weird though.

**Comment by MatthewEppelsheimer** [comment] 2018-10-25 20:09
Duplicate of https://github.com/workshopper/learnyoureact/issues/134

**Closed as completed** 2020-08-11 13:28 UTC
